In [3]:
import pandas as pd
import os

df = pd.read_csv(r'D:\weiyi\data_202201\202201_01_01101010.csv', encoding='latin1')

In [4]:
df

,ªèÇR[h,út,,SO2(ppm),NO(ppm),NO2(ppm),NOx(ppm),CO(ppm),Ox(ppm),NMHC(ppmC),CH4(ppmC),THC(ppmC),SPM(mg/m3),PM2.5(Êg/m3),SP(mg/m3),WD(16Dir),WS(m/s),TEMP(),HUM()
0,1101010,2022/01/01,1,0.000,NaN,NaN,NaN,NaN,0.035,0.02,2.02,2.03,0.004,NaN,NaN,NaN,NaN,NaN,NaN
1,1101010,2022/01/01,2,0.000,NaN,NaN,NaN,NaN,0.033,0.01,2.03,2.04,0.001,NaN,NaN,NaN,NaN,NaN,NaN
2,1101010,2022/01/01,3,0.000,NaN,NaN,NaN,NaN,0.033,0.01,2.02,2.03,0.001,NaN,NaN,NaN,NaN,NaN,NaN
3,1101010,2022/01/01,4,0.000,NaN,NaN,NaN,NaN,0.032,0.01,2.02,2.04,0.003,NaN,NaN,NaN,NaN,NaN,NaN
4,1101010,2022/01/01,5,0.000,NaN,NaN,NaN,NaN,0.031,0.01,2.02,2.04,0.002,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
677,1101010,2022/01/31,20,0.002,NaN,NaN,NaN,NaN,0.014,0.10,2.09,2.18,0.004,NaN,NaN,NaN,NaN,NaN,NaN
678,1101010,2022/01/31,21,0.002,NaN,NaN,NaN,NaN,0.014,0.07,2.05,2.12,0.004,NaN,NaN,NaN,NaN,NaN,NaN
679,1101010,2022/01/31,22,0.003,NaN,NaN,NaN,NaN,0.005,0.13,2.12,2.25,0.006,NaN,NaN,NaN,NaN,NaN,NaN
680,1101010,2022/01/31,23,0.003,NaN,NaN,NaN,NaN,0.002,0.12,2.10,2.22,0.008,NaN,NaN,NaN,NaN,NaN,NaN
681,1101010,2022/01/31,24,0.004,NaN,NaN,NaN,NaN,0.002,0.29,2.22,2.52,0.012,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
import pandas as pd
import os

# 指定存放CSV檔案的資料夾路徑
folder_path = r'D:\weiyi\data_202201'

# 創建一個空的DataFrame，用於儲存合併後的數據
merged_data = pd.DataFrame()

# 定義地區代碼和地區名稱的映射字典
region_mapping = {
    '01': '北海道',
    '02': '東北',
    '03': '東北',
    '04': '東北',
    '05': '東北',
    '06': '東北',
    '07': '東北',
    '08': '關東',
    '09': '關東',
    '10': '關東',
    '11': '關東',
    '12': '關東',
    '13': '關東',
    '14': '關東',
    '15': '中部',
    '16': '中部',
    '17': '中部',
    '18': '中部',
    '19': '中部',
    '20': '中部',
    '21': '東海',
    '22': '東海',
    '23': '東海',
    '24': '東海',
    '25': '近畿',
    '26': '近畿',
    '27': '近畿',
    '28': '近畿',
    '29': '近畿',
    '30': '近畿',
    '31': '中國',
    '32': '中國',
    '33': '中國',
    '34': '中國',
    '35': '中國',
    '36': '中國',
    '37': '中國',
    '38': '中國',
    '39': '中國',
    '40': '九州',
    '41': '九州',
    '42': '九州',
    '43': '九州',
    '44': '九州',
    '45': '九州',
    '46': '九州',
    '47': '沖繩'
}

# 遍歷資料夾中的所有檔案
for filename in os.listdir(folder_path):
    if filename.endswith(".csv"):
        # 讀取CSV檔案
        file_path = os.path.join(folder_path, filename)
        df = pd.read_csv(file_path, encoding='latin1')
        
        # 從檔名中提取地區信息
        region_code = filename.split('_')[1]
        region_name = region_mapping.get(region_code, '未知地區')  # 如果地區代碼不存在於字典中，則設置為'未知地區'
        
        # 將地區信息加入DataFrame作為一個新的欄位
        df['Region'] = region_name
        
        df['filename'] = filename
        
        # 將讀取的數據合併到主數據框中
        merged_data = pd.concat([merged_data, df], ignore_index=True)

# 將合併後的數據寫入Excel檔案，並以地區為Sheet名稱分別存儲
excel_output_path = r'D:\weiyi\202201.xlsx'
with pd.ExcelWriter(excel_output_path, engine='xlsxwriter') as writer:
    for region_name in merged_data['Region'].unique():
        region_df = merged_data[merged_data['Region'] == region_name]
        region_df.to_excel(writer, sheet_name=region_name, index=False)

print(f'合併完成，結果已保存至 {excel_output_path}')

合併完成，結果已保存至 合併後的檔案.xlsx

In [6]:
merged_data

,ªèÇR[h,út,,SO2(ppm),NO(ppm),NO2(ppm),NOx(ppm),CO(ppm),Ox(ppm),NMHC(ppmC),CH4(ppmC),THC(ppmC),SPM(mg/m3),PM2.5(Êg/m3),SP(mg/m3),WD(16Dir),WS(m/s),TEMP(),HUM(),Region
0,1101010,2022/01/01,1,0.0,NaN,NaN,NaN,NaN,0.035,0.02,2.02,2.03,0.004,NaN,NaN,NaN,NaN,NaN,NaN,北海道
1,1101010,2022/01/01,2,0.0,NaN,NaN,NaN,NaN,0.033,0.01,2.03,2.04,0.001,NaN,NaN,NaN,NaN,NaN,NaN,北海道
2,1101010,2022/01/01,3,0.0,NaN,NaN,NaN,NaN,0.033,0.01,2.02,2.03,0.001,NaN,NaN,NaN,NaN,NaN,NaN,北海道
3,1101010,2022/01/01,4,0.0,NaN,NaN,NaN,NaN,0.032,0.01,2.02,2.04,0.003,NaN,NaN,NaN,NaN,NaN,NaN,北海道
4,1101010,2022/01/01,5,0.0,NaN,NaN,NaN,NaN,0.031,0.01,2.02,2.04,0.002,NaN,NaN,NaN,NaN,NaN,NaN,北海道
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257756,11229510,2022/01/31,20,NaN,0.002,0.012,0.014,NaN,NaN,NaN,NaN,NaN,0.007,5,NaN,N,0.5,NaN,NaN,關東
257757,11229510,2022/01/31,21,NaN,0.001,0.012,0.013,NaN,NaN,NaN,NaN,NaN,0.007,6,NaN,CALM,0.4,NaN,NaN,關東
257758,11229510,2022/01/31,22,NaN,0.002,0.013,0.015,NaN,NaN,NaN,NaN,NaN,0.005,5,NaN,W,0.5,NaN,NaN,關東
257759,11229510,2022/01/31,23,NaN,0.001,0.020,0.021,NaN,NaN,NaN,NaN,NaN,0.008,5,NaN,CALM,0.0,NaN,NaN,關東
257760,11229510,2022/01/31,24,NaN,0.001,0.022,0.023,NaN,NaN,NaN,NaN,NaN,0.010,8,NaN,CALM,0.2,NaN,NaN,關東